### PR TITLE
[PREVIEW] Change Vault name to include the actual product

### PR DESCRIPTION
**Pull request by lgonczar**
### Change description ###

Change Vault name to include the actual product. Currently, it's just `rpe-{env}`.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by timja** [comment]
Be aware this will delete the old vault and create a new vault

**Comment by lgonczar** [comment]
Fortunately, all the values are populated in terraform

**Comment by timja** [comment]
Ok that needs to be removed in a follow up PR after we've migrated the secrets into a new vault

**Comment by timja** [comment]
i meant the resource that retrieves them from hashi vault and writes them in, we need to stop touching hashi vault as part of this story

**Pull request merged**
