### PR TITLE
Add stitching API

### PR DESCRIPTION
**Pull request by linusnorton**
# JIRA link (if applicable)

N/A

# Change description

added new microservice key EM_STITCHING_API to get s2s token.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by timja** [comment]
The PR template hasn't been filled out...

**Comment by linusnorton** [comment]
@nitinprabhu I don't believe there are any new secrets

**Comment by linusnorton** [comment]
@nitinprabhu / @timja do I still run that script if there are no new secrets?

**Comment by timja** [comment]
You can't add a new key without there being new secrets too

**Comment by linusnorton** [comment]
@timja the output from that command is:

```
INFO: Found secret microservicekey-em-stitching-api in environment sandbox
INFO: Found secret microservicekey-em-stitching-api in environment saat
INFO: Found secret microservicekey-em-stitching-api in environment sprod
INFO: Found secret microservicekey-em-stitching-api in environment demo
```
INFO: Found secret microservicekey-em-stitching-api in environment hmctsdemo
INFO: Found secret microservicekey-em-stitching-api in environment aat
INFO: Found secret microservicekey-em-stitching-api in environment prod

**Pull request merged**
